### ISSUE TITLE
Thumbnail is not displayed after insertion image.

### ISSUE THREAD

**Issue by sectsect** [drewrawitz/wp-featured-image-notes#1]
Hi, Thanks for the useful plugin.

When I inserted the Featured image, I found a bug that thumbnail is not displayed.

I guess it is because the 'post' sent to the admin-ajax.php does not hold the 'data' attribute.

Can you solve this?
- Ajax when i **enable** this plugin
  <img width="569" alt="capture 2016-07-04 at 19 41 02" src="https://cloud.githubusercontent.com/assets/5554826/16558532/4a843650-4221-11e6-991a-db723d49d51b.png">
- Ajax when i **disable** this plugin
  <img width="672" alt="capture 2016-07-04 at 19 42 19" src="https://cloud.githubusercontent.com/assets/5554826/16558541/5bdd1afc-4221-11e6-8863-113b296d09a3.png">

**Comment by drewrawitz** [comment]
@sectsect Thanks for submitting an issue!  I went ahead and made some commits to address this issue. Pull down the latest and let me know how that works for you. I'm in the process of tagging a new release for the official WP plugin repository as well. 

Thank you!

**Comment by sectsect** [comment]
Thanks for quick response. It works fine by the bug fixes.
Thank you. And good day.
